### ISSUE TITLE
Issue while running demo

### ISSUE THREAD

**Issue by ddliugit** [machines-in-motion/pinocchio_bullet#2]
I just run demo and it needs a module:
robot_properties_solo.config
Where can I get it
Another prob: should this package be run under ros environment

**Comment by jviereck** [comment]
hi @ddliugit , thanks for pointing out this issue.

You can find the robot_properties_solo package in this repo [1].

The robot_properties_solo package is a catkin package. You don't need a full ros environment but at least a basic catkin workspace and xacro compiler support.

Please let me know if this works or you have any further questions.

Best,
Julian

[1]: https://github.com/open-dynamic-robot-initiative/robot_properties_solo/

**Comment by ddliugit** [comment]
Thanks. 
I find the package and now it works pretty well.
